### ISSUE TITLE
After shortening a Google image search URL, the shortened URL was a normal Google search URL.

### ISSUE THREAD

**Issue by tyomhk2015** [serranoarevalo/huchulink#1]
Greetings Nicolas! 👋

This is just purely asking a question about your Huchulink.

I tried your Huchulink service, and found something that I did not expect. 

💡 What I was expecting from Huchulink's shortend URL:
> Google's image search result page.
<img src="https://user-images.githubusercontent.com/35278730/141672161-e4b8e8af-8b88-4d0d-a10e-92c293b327ac.png" width="600" alt="Expected result">

💀 What I actually got from Huchulink's shortend URL:
> Google's overall search result page.
<img src="https://user-images.githubusercontent.com/35278730/141672166-d3646324-8ce6-41fd-ae29-e9b8244a3138.png" width="600"  alt="Actual result">

⚠️ The steps I took is as the following.
<pre>
1. Visited https://huchu.link/.
2. Searched 'scaffold' at Google.com.
3. After overall search results shows, clicked 'image' tab.
4. Copied URL of the 'image' search result.
5. Pasted the URL in Huchulink's input.
6. After the shortened URL are shown below the input, copied the  URL.
7. Pasted the URL in the address bar of the browser and hit enter key.
8. The page that huchulink's shortened URL showed was not 'image' search result, but 'overall' search result of scaffold.
</pre>

I was wondering 
(1) if this behavior was intended at the beginning of Huchulink's plan, 
(2) and will there be some improvement about returning unexpected URL, the shortened one.

If this post made you uncomfortable, or if I breached any policies of Nomad Coders, I truly apologize for it.

Thank you for your time reading this post! 

Keep up the good work! 💪

<br>
Sincerely,  a student of Nomad Coders, <a href="https://nomadcoders.co/users/tyomhk2015" target="_blank" rel="noopener">Tyo</a>

**Comment by serranoarevalo** [comment]
Thanks a lot! It's fixed now :)
